# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               A Random Developer
tagline:             'Hack the World!'
baseurl:             ''
paginate:            5
paginate_path:       "/blog/:num/"
excerpt_separator:   <!--more-->

collections:
  projects:
    output:          true

# About/contact
author:
  name:              Matthew (Willow) Willard
  url:               https://twitter.com/matthewwwillard
  email:             matt@arandomdeveloper.com
  twitter:           https://twitter.com/matthewwwillard
  github:            https://github.com/matthewwwillard

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate
